allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true

overrides:
  "vite": "catalog:"
  "vitest": "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10
  vite-plus: latest
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
